import { Inter } from "next/font/google";
import Header from "@/components/Header";
import "@/assets/styles/globals.css";

const inter = Inter({subsets:['latin']});

export const metadata = {
  title: "The Black Banshee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='${inter.className} bg-white text-black'>
        <Header></Header>
        <main className="mx-auto max-w-7xl px-4 py-6 sm:px-4 lg:px-8">
          {children}
        </main>
        </body>
    </html>
  );
}
